# Dashboard Data Preparation

This notebook prepares the final dataset for Power BI.

The objectives are:

- Create a clean dashboard-ready dataset
- Validate data quality
- Export the final dataset
- Prepare KPI metrics

In [1]:
import pandas as pd

In [2]:
sales = pd.read_csv("../data/processed/sales_clean.csv")

sales.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,review_creation_date,review_answer_timestamp,seller_zip_code_prefix,seller_city,seller_state,purchase_year,purchase_month,purchase_day,delivery_days,total_sales
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2017-10-11,2017-10-12 03:43:48,9350.0,maua,SP,2017,October,Monday,8.0,38.71
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2017-10-11,2017-10-12 03:43:48,9350.0,maua,SP,2017,October,Monday,8.0,38.71
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2017-10-11,2017-10-12 03:43:48,9350.0,maua,SP,2017,October,Monday,8.0,38.71
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,2018-08-08,2018-08-08 18:37:50,31570.0,belo horizonte,SP,2018,July,Tuesday,13.0,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,2018-08-18,2018-08-22 19:07:58,14840.0,guariba,SP,2018,August,Wednesday,9.0,179.12

In [3]:
dashboard = sales[
    [
        "order_id",
        "customer_unique_id",
        "customer_city",
        "customer_state",
        "purchase_year",
        "purchase_month",
        "purchase_day",
        "product_category_name_english",
        "price",
        "freight_value",
        "total_sales",
        "payment_type",
        "payment_installments",
        "review_score",
        "delivery_days",
        "order_status"
    ]
]

In [4]:
dashboard.head()

,order_id,customer_unique_id,customer_city,customer_state,purchase_year,purchase_month,purchase_day,product_category_name_english,price,freight_value,total_sales,payment_type,payment_installments,review_score,delivery_days,order_status
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,2017,October,Monday,housewares,29.99,8.72,38.71,credit_card,1.0,4.0,8.0,delivered
1,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,2017,October,Monday,housewares,29.99,8.72,38.71,voucher,1.0,4.0,8.0,delivered
2,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,2017,October,Monday,housewares,29.99,8.72,38.71,voucher,1.0,4.0,8.0,delivered
3,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,barreiras,BA,2018,July,Tuesday,perfumery,118.70,22.76,141.46,boleto,1.0,4.0,13.0,delivered
4,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,2018,August,Wednesday,auto,159.90,19.22,179.12,credit_card,3.0,5.0,9.0,delivered

In [5]:
dashboard = dashboard.rename(
    columns={
        "customer_unique_id":"Customer ID",
        "customer_city":"City",
        "customer_state":"State",
        "purchase_year":"Year",
        "purchase_month":"Month",
        "purchase_day":"Day",
        "product_category_name_english":"Category",
        "price":"Product Price",
        "freight_value":"Shipping Cost",
        "total_sales":"Revenue",
        "payment_type":"Payment Method",
        "payment_installments":"Installments",
        "review_score":"Review Score",
        "delivery_days":"Delivery Days",
        "order_status":"Order Status"
    }
)

dashboard.head()

,order_id,Customer ID,City,State,Year,Month,Day,Category,Product Price,Shipping Cost,Revenue,Payment Method,Installments,Review Score,Delivery Days,Order Status
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,2017,October,Monday,housewares,29.99,8.72,38.71,credit_card,1.0,4.0,8.0,delivered
1,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,2017,October,Monday,housewares,29.99,8.72,38.71,voucher,1.0,4.0,8.0,delivered
2,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,2017,October,Monday,housewares,29.99,8.72,38.71,voucher,1.0,4.0,8.0,delivered
3,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,barreiras,BA,2018,July,Tuesday,perfumery,118.70,22.76,141.46,boleto,1.0,4.0,13.0,delivered
4,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,2018,August,Wednesday,auto,159.90,19.22,179.12,credit_card,3.0,5.0,9.0,delivered

In [6]:
dashboard.shape

(119143, 16)

In [7]:
dashboard.isnull().sum()

order_id             0
Customer ID          0
City                 0
State                0
Year                 0
Month                0
Day                  0
Category          2568
Product Price      833
Shipping Cost      833
Revenue            833
Payment Method       3
Installments         3
Review Score       997
Delivery Days     3421
Order Status         0
dtype: int64

In [8]:
dashboard.duplicated().sum()

np.int64(14039)

In [9]:
dashboard.dtypes

order_id           object
Customer ID        object
City               object
State              object
Year                int64
Month              object
Day                object
Category           object
Product Price     float64
Shipping Cost     float64
Revenue           float64
Payment Method     object
Installments      float64
Review Score      float64
Delivery Days     float64
Order Status       object
dtype: object

In [10]:
dashboard["Revenue"].sum()

np.float64(16643731.3)

In [11]:
dashboard["order_id"].nunique()

99441

In [12]:
dashboard["Customer ID"].nunique()

96096

In [13]:
dashboard["Delivery Days"].mean()

np.float64(12.022588617548953)

In [14]:
dashboard["Review Score"].mean()

np.float64(4.015582414978078)

In [15]:
repeat_rate = (
    dashboard
    .groupby("Customer ID")["order_id"]
    .nunique()
)

(
    (repeat_rate>1).sum()
    /
    repeat_rate.count()
    *100
)

np.float64(3.1187562437562435)

In [17]:
dashboard["Date"] = pd.to_datetime(
    sales["order_purchase_timestamp"]
)

In [19]:
dashboard = dashboard.sort_values("Date")

In [20]:
dashboard.head()

,order_id,Customer ID,City,State,Year,Month,Day,Category,Product Price,Shipping Cost,Revenue,Payment Method,Installments,Review Score,Delivery Days,Order Status,Date
5359,2e7a8482f6fb09756ca50c10d7bfc047,b7d76e111c89f7ebf14761390f0f7d17,boa vista,RR,2016,September,Sunday,furniture_decor,39.99,31.67,71.66,credit_card,1.0,1.0,NaN,shipped,2016-09-04 21:15:19
5360,2e7a8482f6fb09756ca50c10d7bfc047,b7d76e111c89f7ebf14761390f0f7d17,boa vista,RR,2016,September,Sunday,furniture_decor,32.90,31.67,64.57,credit_card,1.0,1.0,NaN,shipped,2016-09-04 21:15:19
5198,e5fa5a7210941f7d56d0208e4e071d35,4854e9b3feff728c13ee5fc7d1547e92,passo fundo,RS,2016,September,Monday,telephony,59.50,15.56,75.06,credit_card,3.0,1.0,NaN,canceled,2016-09-05 00:15:34
11996,809a282bbd5dbcabb6f2f724fca862ec,009b0127b727ab0ba422f6d9604487c7,sao jose dos campos,SP,2016,September,Tuesday,NaN,NaN,NaN,NaN,credit_card,2.0,1.0,NaN,canceled,2016-09-13 15:24:19
36864,bfbd0f9bdef84302105ad712db648a6c,830d5b7aaa3b6f1e9ad63703bec97d23,sao joaquim da barra,SP,2016,September,Thursday,health_beauty,44.99,2.83,47.82,NaN,NaN,1.0,54.0,delivered,2016-09-15 12:16:38

In [21]:
dashboard.tail()

,order_id,Customer ID,City,State,Year,Month,Day,Category,Product Price,Shipping Cost,Revenue,Payment Method,Installments,Review Score,Delivery Days,Order Status,Date
60308,392ed9afd714e3c74767d0c4d3e3f477,9bb92bebd4cb7511e1a02d5e50bc4655,guarulhos,SP,2018,September,Saturday,NaN,NaN,NaN,NaN,voucher,1.0,1.0,NaN,canceled,2018-09-29 09:13:03
105869,616fa7d4871b87832197b2a137a115d2,634420a0ea42302205032ed44ac7fccc,pirai,RJ,2018,October,Monday,NaN,NaN,NaN,NaN,voucher,1.0,2.0,NaN,canceled,2018-10-01 15:30:09
38270,a2ac6dad85cf8af5b0afb510a240fe8c,af5454198a97379394cacf676e1e96cb,registro,SP,2018,October,Wednesday,NaN,NaN,NaN,NaN,voucher,1.0,1.0,NaN,canceled,2018-10-03 18:55:29
81748,b059ee4de278302d550a3035c4cdb740,262e1f1e26e92e86375f86840b4ffd63,picos,PI,2018,October,Tuesday,NaN,NaN,NaN,NaN,voucher,1.0,5.0,NaN,canceled,2018-10-16 20:16:02
72820,10a045cdf6a5650c21e9cfeb60384c16,87ab9fec999db8bd5774917de3cdf01c,sorocaba,SP,2018,October,Wednesday,NaN,NaN,NaN,NaN,voucher,1.0,1.0,NaN,canceled,2018-10-17 17:30:18

In [22]:
dashboard.to_csv(
    "../data/processed/dashboard_data.csv",
    index=False
)

In [23]:
check = pd.read_csv("../data/processed/dashboard_data.csv")

check.head()

,order_id,Customer ID,City,State,Year,Month,Day,Category,Product Price,Shipping Cost,Revenue,Payment Method,Installments,Review Score,Delivery Days,Order Status,Date
0,2e7a8482f6fb09756ca50c10d7bfc047,b7d76e111c89f7ebf14761390f0f7d17,boa vista,RR,2016,September,Sunday,furniture_decor,39.99,31.67,71.66,credit_card,1.0,1.0,NaN,shipped,2016-09-04 21:15:19
1,2e7a8482f6fb09756ca50c10d7bfc047,b7d76e111c89f7ebf14761390f0f7d17,boa vista,RR,2016,September,Sunday,furniture_decor,32.90,31.67,64.57,credit_card,1.0,1.0,NaN,shipped,2016-09-04 21:15:19
2,e5fa5a7210941f7d56d0208e4e071d35,4854e9b3feff728c13ee5fc7d1547e92,passo fundo,RS,2016,September,Monday,telephony,59.50,15.56,75.06,credit_card,3.0,1.0,NaN,canceled,2016-09-05 00:15:34
3,809a282bbd5dbcabb6f2f724fca862ec,009b0127b727ab0ba422f6d9604487c7,sao jose dos campos,SP,2016,September,Tuesday,NaN,NaN,NaN,NaN,credit_card,2.0,1.0,NaN,canceled,2016-09-13 15:24:19
4,bfbd0f9bdef84302105ad712db648a6c,830d5b7aaa3b6f1e9ad63703bec97d23,sao joaquim da barra,SP,2016,September,Thursday,health_beauty,44.99,2.83,47.82,NaN,NaN,1.0,54.0,delivered,2016-09-15 12:16:38

## Dashboard Dataset Successfully Exported

File:

data/processed/dashboard_data.csv

This dataset is ready to be imported into Power BI.